name: PlinkTests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.11']
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install -v
      working-directory: ./plinkAPI
      shell: bash
    - name: Test with tox
      run: tox
      working-directory: ./plinkAPI